---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

# adding 10 seconds timmer
resources:
  - name: spring-boot-service
    type: pull-request
    check_every: 10s
    source:
      uri: https://github.com/GauravGithubbox/CodeInsides.git
      branch: master

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

#  - name: kubectl
#    type: kubectl-resource
#    source:
#      api_server_uri: ((server))
#      namespace: ((namespace))
#      certificate_authority_data: ((cad))
#      token: ((token))

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        file: "spring-boot-service/Concourse-Ci/tasks/maven-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        file: "spring-boot-service/Concourse-Ci/tasks/maven-package.yml"
      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out

#  - name: deploy
#    public: true
#    serial: true
#    plan:
#      - get: spring-boot-service
#        trigger: false
#        passed: [package]
#
#      - put: kubectl
#        params:
#          file: "spring-boot-service/spring-boot-deploy.yaml"